### ISSUE TITLE
⭐ Использование одинаковых классов

### ISSUE THREAD

**Issue by nastiia-dev** [Yuliko-L/task-1#3]
Для одинаковых блоков нужно использовать одинаковые классы. 
Например, вот у тебя в коде есть блоки: 
```html
<div class="prices">
    <div class="price_1">
        ...
        <button class="ghost-button">Create account</button>
    </div>
    <div class="price_2">
        ...
        <button class="ghost-button">Create account</button>
    </div>
    <div class="price_3">
        ...
        <button class="ghost-button">Create account</button>
    </div>
</div>
```
В стилях, в таком случае, тебе приходится сначала все описать для класса `.price_1`, потом делать наследование для `.price_2` и `.price_3`. В результате дублируется много одинакового кода (это можно посмотреть в файле, который создается с расширением `.css`)
Блоки выглядят полностью одинаковыми, отличие - кнопка. Значит, для всех трех блоков нужно указать одинаковый класс. А для кнопки, которая отличается, через пробел, указать класс, который будет менять ее цвет (все параметры, кроме цветов, совпадают). 

**Например, твой код перепишеться (html):**

```html
<div class="prices">
    <div class="price">
        ...
        <button class="ghost-button">Create account</button>
    </div>
    <div class="price">
        ...
        <button class="ghost-button blue-button">Create account</button>
    </div>
    <div class="price">
        ...
        <button class="ghost-button">Create account</button>
    </div>
</div>
``` 

**и тогда в style.scss:**

```scss
.prices {
    ...

    .price {
        position: relative;
        width: 390px;
        height: 510px;
        background-color: white;
        border-radius: 1.6em;
        border: none;
        box-shadow: 0px 10px 20px 0px rgba(0, 40, 100, 0.25);        

        .ghost-button {
            width: 222px;
            height: 63px;
            background-color: white;
            border-radius: 0.8em;
            border: 1px solid #cccccc;
            position: absolute;
            bottom: 37px;
            left: 84px;
            @include text(1.8rem, 600, 2.7rem, #cccccc);

        }
        
        .blue-button{
            background-color: $blue;
            @include text(1.8rem, 600, 2.7rem, white);
        }
        ...
        ...
        ...
    }
}
```
где ... - остальной твой код
