### ISSUE TITLE
⭐ Использование одинаковых классов по БЭМу

### ISSUE THREAD

**Issue by nastiia-dev** [Yuliko-L/task-1#4]
Если следовать методологии БЭМ, то, код нужно исправить следующим образом
**index.html:** 
```html
<div class="prices">
    <div class="prices__item">
        <p class="prices__name">
            Free
        </p>
        <p class="prices__number">$0</p>
        <ul>
            <li>500 visitors</li>
            <li>Unlimited projects</li>
            <li>extended free trial</li>
        </ul>
        <button class="prices__button">Create account</button>
    </div>
    <div class="prices__item">
        <p class="prices__name">
            Standard
        </p>
        <p class="prices__number">
            $99
        </p>
        <ul>
            <li>10000 visitors</li>
            <li>Unlimited projects</li>
            <li>extended free trial</li>
        </ul>
        <button class="prices__button prices__button--active">Create account</button>
    </div>
    <div class="prices__item">
        <p class="prices__name">
            Enterprise
        </p>
        <p class="prices__number">Let’s talk!</p>
        <ul>
            <li>10000+ visitors</li>
            <li>Unlimited projects</li>
            <li>extended free trial</li>
        </ul>
        <button class="prices__button">Create account</button>
    </div>
</div>
```

файл **style.scss** перепишеться так: 
```scss
.prices {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 40px;
    margin-top: 80px;
    margin-bottom: 180px;

    &__item {
        position: relative;
        width: 390px;
        height: 510px;
        background-color: white;
        border-radius: 1.6em;
        border: none;
        box-shadow: 0px 10px 20px 0px rgba(0, 40, 100, 0.25);            

        ul {
            margin-left: 36px;
            margin-top: 64px;
            list-style: none;
            @include text (1.8rem, 400, 2.7rem, black);

            li {
                margin-top: 24px;

                &::before{
                    color: $blue;
                content: url(./marker.svg);
                margin-right: 15px;
                }
            }
        }
    }

    &__name {
        @include text(2.4rem, 600, 2.9rem, black);
        text-align: center;
        margin-top: 32px;
    }

    &__number {
        @include text(4rem, 700, 4.8rem, black);
        text-align: center;
        margin-top: 16px;
    }

    &__button {
            width: 222px;
            height: 63px;
            background-color: white;
            border-radius: 0.8em;
            border: 1px solid #cccccc;
            position: absolute;
            bottom: 37px;
            left: 84px;
            @include text(1.8rem, 600, 2.7rem, #cccccc);

            &--active{
                background-color: $blue;
                @include text(1.8rem, 600, 2.7rem, white);
            }

        }

    }

    &::after{
        content: "";
        display: block;
        width: 100%;
        height: 519px;
        background-image: url(./wave.svg);
        position: absolute;
        bottom: 0px;
        z-index: -1;
    }
}
```
