### ISSUE TITLE
⭐ Наследование в файле SCSS

### ISSUE THREAD

**Issue by nastiia-dev** [Yuliko-L/task-1#5]
Не нужно делать наследование в середине html (т.е. все прописывать внутри него): 

**было**: 
```scss
html {
    font-size: 62.5%;
    position: relative;
    z-index: 1;

    h1 {
        @include text (4rem, 700, 4.8rem, black);
        text-align: center;
        margin-top: 80px;
    }

    .title-text {
        @include text (1.6rem, 500, 2.8rem, black);
        text-align: center;
        margin-top: 40px;
    }
    ...
}
```
**стало** (после описания всего необходимого для html, закрываем фигурную скобку): 
```scss
html {
    font-size: 62.5%;
    position: relative;
    z-index: 1;
}

h1 {
    @include text (4rem, 700, 4.8rem, black);
    text-align: center;
    margin-top: 80px;
}

.title-text {
    @include text (1.6rem, 500, 2.8rem, black);
    text-align: center;
    margin-top: 40px;
}
...

```
